### ISSUE TITLE
Submodule missing?

### ISSUE THREAD

**Issue by Clemens123** [Babelscape/crocodile#1]
Hi! Firstly, thanks for publishing your research implementation!
I'm just missing the files in ./wikiextractor as described in the setup instructions:

> For ./wikiextractor we use a submodule which is a fork of the original wikiextractor that implements wikimapper to extract the Wikidata entities.

Maybe the submodule is missing?

**Comment by LittlePea13** [comment]
Hi there,

Thanks for the issue! Indeed, I am not very familiar with the usage of submodules, I have to take another look at it since I believe something went wrong when I made the repos public. In the meantime, you can find the modified version of wikiextractor here, that's the submodule that is missing, just clone it on the same location.

https://github.com/LittlePea13/wikiextractor

Best,
Pere-Lluis.
